// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package strombotne.spencer.kitchenmanager.domain;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import strombotne.spencer.kitchenmanager.domain.Ingredient;
import strombotne.spencer.kitchenmanager.domain.IngredientType;

privileged aspect IngredientDataOnDemand_Roo_DataOnDemand {
    
    declare @type: IngredientDataOnDemand: @Component;
    
    private Random IngredientDataOnDemand.rnd = new SecureRandom();
    
    private List<Ingredient> IngredientDataOnDemand.data;
    
    public Ingredient IngredientDataOnDemand.getNewTransientIngredient(int index) {
        Ingredient obj = new Ingredient();
        setCreated(obj, index);
        setDisplayName(obj, index);
        setType(obj, index);
        return obj;
    }
    
    public void IngredientDataOnDemand.setCreated(Ingredient obj, int index) {
        Date created = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreated(created);
    }
    
    public void IngredientDataOnDemand.setDisplayName(Ingredient obj, int index) {
        String displayName = "displayName_" + index;
        obj.setDisplayName(displayName);
    }
    
    public void IngredientDataOnDemand.setType(Ingredient obj, int index) {
        IngredientType type = IngredientType.class.getEnumConstants()[0];
        obj.setType(type);
    }
    
    public Ingredient IngredientDataOnDemand.getSpecificIngredient(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Ingredient obj = data.get(index);
        return Ingredient.findIngredient(obj.getId());
    }
    
    public Ingredient IngredientDataOnDemand.getRandomIngredient() {
        init();
        Ingredient obj = data.get(rnd.nextInt(data.size()));
        return Ingredient.findIngredient(obj.getId());
    }
    
    public boolean IngredientDataOnDemand.modifyIngredient(Ingredient obj) {
        return false;
    }
    
    public void IngredientDataOnDemand.init() {
        data = Ingredient.findIngredientEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Ingredient' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<strombotne.spencer.kitchenmanager.domain.Ingredient>();
        for (int i = 0; i < 10; i++) {
            Ingredient obj = getNewTransientIngredient(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
