// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package strombotne.spencer.kitchenmanager.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import strombotne.spencer.kitchenmanager.domain.LoginDataOnDemand;

privileged aspect LoginIntegrationTest_Roo_IntegrationTest {
    
    declare @type: LoginIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: LoginIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: LoginIntegrationTest: @Transactional;
    
    @Autowired
    private LoginDataOnDemand LoginIntegrationTest.dod;
    
    @Test
    public void LoginIntegrationTest.testCountLogins() {
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to initialize correctly", dod.getRandomLogin());
        long count = strombotne.spencer.kitchenmanager.domain.Login.countLogins();
        org.junit.Assert.assertTrue("Counter for 'Login' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void LoginIntegrationTest.testFindLogin() {
        strombotne.spencer.kitchenmanager.domain.Login obj = dod.getRandomLogin();
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to provide an identifier", id);
        obj = strombotne.spencer.kitchenmanager.domain.Login.findLogin(id);
        org.junit.Assert.assertNotNull("Find method for 'Login' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Login' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void LoginIntegrationTest.testFindAllLogins() {
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to initialize correctly", dod.getRandomLogin());
        long count = strombotne.spencer.kitchenmanager.domain.Login.countLogins();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Login', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<strombotne.spencer.kitchenmanager.domain.Login> result = strombotne.spencer.kitchenmanager.domain.Login.findAllLogins();
        org.junit.Assert.assertNotNull("Find all method for 'Login' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Login' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void LoginIntegrationTest.testFindLoginEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to initialize correctly", dod.getRandomLogin());
        long count = strombotne.spencer.kitchenmanager.domain.Login.countLogins();
        if (count > 20) count = 20;
        java.util.List<strombotne.spencer.kitchenmanager.domain.Login> result = strombotne.spencer.kitchenmanager.domain.Login.findLoginEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Login' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Login' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void LoginIntegrationTest.testFlush() {
        strombotne.spencer.kitchenmanager.domain.Login obj = dod.getRandomLogin();
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to provide an identifier", id);
        obj = strombotne.spencer.kitchenmanager.domain.Login.findLogin(id);
        org.junit.Assert.assertNotNull("Find method for 'Login' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyLogin(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Login' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LoginIntegrationTest.testMerge() {
        strombotne.spencer.kitchenmanager.domain.Login obj = dod.getRandomLogin();
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to provide an identifier", id);
        obj = strombotne.spencer.kitchenmanager.domain.Login.findLogin(id);
        boolean modified =  dod.modifyLogin(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        strombotne.spencer.kitchenmanager.domain.Login merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Login' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void LoginIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to initialize correctly", dod.getRandomLogin());
        strombotne.spencer.kitchenmanager.domain.Login obj = dod.getNewTransientLogin(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Login' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Login' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void LoginIntegrationTest.testRemove() {
        strombotne.spencer.kitchenmanager.domain.Login obj = dod.getRandomLogin();
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Login' failed to provide an identifier", id);
        obj = strombotne.spencer.kitchenmanager.domain.Login.findLogin(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Login' with identifier '" + id + "'", strombotne.spencer.kitchenmanager.domain.Login.findLogin(id));
    }
    
}
