// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package strombotne.spencer.kitchenmanager.domain;

import java.lang.Boolean;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import strombotne.spencer.kitchenmanager.domain.Login;

privileged aspect LoginDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LoginDataOnDemand: @Component;
    
    private Random LoginDataOnDemand.rnd = new SecureRandom();
    
    private List<Login> LoginDataOnDemand.data;
    
    public Login LoginDataOnDemand.getNewTransientLogin(int index) {
        Login obj = new Login();
        setEnabled(obj, index);
        setPassword(obj, index);
        setUsername(obj, index);
        return obj;
    }
    
    public void LoginDataOnDemand.setEnabled(Login obj, int index) {
        Boolean enabled = Boolean.TRUE;
        obj.setEnabled(enabled);
    }
    
    public void LoginDataOnDemand.setPassword(Login obj, int index) {
        String password = "password_" + index;
        if (password.length() > 100) {
            password = password.substring(0, 100);
        }
        obj.setPassword(password);
    }
    
    public void LoginDataOnDemand.setUsername(Login obj, int index) {
        String username = "username_" + index;
        if (username.length() > 15) {
            username = username.substring(0, 15);
        }
        obj.setUsername(username);
    }
    
    public Login LoginDataOnDemand.getSpecificLogin(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Login obj = data.get(index);
        return Login.findLogin(obj.getId());
    }
    
    public Login LoginDataOnDemand.getRandomLogin() {
        init();
        Login obj = data.get(rnd.nextInt(data.size()));
        return Login.findLogin(obj.getId());
    }
    
    public boolean LoginDataOnDemand.modifyLogin(Login obj) {
        return false;
    }
    
    public void LoginDataOnDemand.init() {
        data = Login.findLoginEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Login' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<strombotne.spencer.kitchenmanager.domain.Login>();
        for (int i = 0; i < 10; i++) {
            Login obj = getNewTransientLogin(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
