// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package strombotne.spencer.kitchenmanager.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import strombotne.spencer.kitchenmanager.domain.UserAuthorityDataOnDemand;

privileged aspect UserAuthorityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: UserAuthorityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: UserAuthorityIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: UserAuthorityIntegrationTest: @Transactional;
    
    @Autowired
    private UserAuthorityDataOnDemand UserAuthorityIntegrationTest.dod;
    
    @Test
    public void UserAuthorityIntegrationTest.testCountUserAuthoritys() {
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to initialize correctly", dod.getRandomUserAuthority());
        long count = strombotne.spencer.kitchenmanager.domain.UserAuthority.countUserAuthoritys();
        org.junit.Assert.assertTrue("Counter for 'UserAuthority' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void UserAuthorityIntegrationTest.testFindUserAuthority() {
        strombotne.spencer.kitchenmanager.domain.UserAuthority obj = dod.getRandomUserAuthority();
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to provide an identifier", id);
        obj = strombotne.spencer.kitchenmanager.domain.UserAuthority.findUserAuthority(id);
        org.junit.Assert.assertNotNull("Find method for 'UserAuthority' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'UserAuthority' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void UserAuthorityIntegrationTest.testFindAllUserAuthoritys() {
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to initialize correctly", dod.getRandomUserAuthority());
        long count = strombotne.spencer.kitchenmanager.domain.UserAuthority.countUserAuthoritys();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'UserAuthority', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<strombotne.spencer.kitchenmanager.domain.UserAuthority> result = strombotne.spencer.kitchenmanager.domain.UserAuthority.findAllUserAuthoritys();
        org.junit.Assert.assertNotNull("Find all method for 'UserAuthority' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'UserAuthority' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void UserAuthorityIntegrationTest.testFindUserAuthorityEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to initialize correctly", dod.getRandomUserAuthority());
        long count = strombotne.spencer.kitchenmanager.domain.UserAuthority.countUserAuthoritys();
        if (count > 20) count = 20;
        java.util.List<strombotne.spencer.kitchenmanager.domain.UserAuthority> result = strombotne.spencer.kitchenmanager.domain.UserAuthority.findUserAuthorityEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'UserAuthority' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'UserAuthority' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void UserAuthorityIntegrationTest.testFlush() {
        strombotne.spencer.kitchenmanager.domain.UserAuthority obj = dod.getRandomUserAuthority();
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to provide an identifier", id);
        obj = strombotne.spencer.kitchenmanager.domain.UserAuthority.findUserAuthority(id);
        org.junit.Assert.assertNotNull("Find method for 'UserAuthority' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyUserAuthority(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'UserAuthority' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserAuthorityIntegrationTest.testMerge() {
        strombotne.spencer.kitchenmanager.domain.UserAuthority obj = dod.getRandomUserAuthority();
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to provide an identifier", id);
        obj = strombotne.spencer.kitchenmanager.domain.UserAuthority.findUserAuthority(id);
        boolean modified =  dod.modifyUserAuthority(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        strombotne.spencer.kitchenmanager.domain.UserAuthority merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'UserAuthority' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void UserAuthorityIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to initialize correctly", dod.getRandomUserAuthority());
        strombotne.spencer.kitchenmanager.domain.UserAuthority obj = dod.getNewTransientUserAuthority(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'UserAuthority' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'UserAuthority' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void UserAuthorityIntegrationTest.testRemove() {
        strombotne.spencer.kitchenmanager.domain.UserAuthority obj = dod.getRandomUserAuthority();
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'UserAuthority' failed to provide an identifier", id);
        obj = strombotne.spencer.kitchenmanager.domain.UserAuthority.findUserAuthority(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'UserAuthority' with identifier '" + id + "'", strombotne.spencer.kitchenmanager.domain.UserAuthority.findUserAuthority(id));
    }
    
}
